### ISSUE TITLE
Camera Permission Request Text

### ISSUE THREAD

**Issue by Mr-Anonymous** [dmcBig/cordova-plugin-mediaPicker#11]
May I ask, how does this plugin use the text when asking for Camera and Photo library access permission? If I have `cordova-plugin-ios-camera-permissions` plugin installed, does it use the permission text defined in that?

At the moment I am using it for Android only which is no problem. But now I am gonna be using this plugin for my iOS App as well. The iOS review team rejects the app if the camera permission request does not give the exact reason on how the media will be used. 

So, is it possible to add our own description for this permission request?

**Comment by dmcBig** [comment]
ok

**Comment by dmcBig** [comment]
Is it convenient for me to tell me the name of your developed app on the App Store?

**Comment by dmcBig** [comment]
@Mr-Anonymous Is it convenient for me to tell me the name of your developed app on the App Store?

**Comment by dmcBig** [comment]
@Mr-Anonymous yes
