### ISSUE TITLE
Android按Back键返回，主Activity刷新的问题

### ISSUE THREAD

**Issue by K68** [dmcBig/cordova-plugin-mediaPicker#13]
环境：
 - Android 8.0.0
- HUAWEI Mate 10  Pro

问题描述：
媒体选择界面出现后，按物理Back键，主Activity会从右侧进入并再次刷新

期待效果：
类似选择图片后点击完成，媒体选择界面从右侧退出屏幕，显示出底下的主Activity

**Comment by dmcBig** [comment]
这估计遇到了crash，造成APP重启了，你最好连接上android studio 看看错误日志。

**Comment by K68** [comment]
![image](https://user-images.githubusercontent.com/9476589/41716056-d7b9e6d2-7587-11e8-9de2-31278bf48231.png)
![image](https://user-images.githubusercontent.com/9476589/41716062-dc6a1972-7587-11e8-908b-59631a44fc2f.png)

**Comment by K68** [comment]
看了一下日志，当点击Back键时，报了上图的错误，v4/view/KeyEventCompat 这个Class找不到，然后导致了程序崩溃

**Comment by dmcBig** [comment]
你有用其他插件嘛？看看你的插件列表 都有些什么插件。

**Comment by K68** [comment]
call-number 1.0.4 "Cordova Call Number Plugin"
com.kit.cordova.amaplocation-liugogal 1.0.4 "LocationPlugin"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-mediapicker-dmcbig 2.2.5 "MediaPicker"
cordova-plugin-photo-library 2.1.1 "Photo Library"
cordova-plugin-video-editor 1.1.3 "VideoEditor"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
cordova-plugin-x5-tbs 1.0.0 "Tencent X5 for Cordova"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"

**Comment by K68** [comment]
问题解决了，参考了这个网址： [](http://bbs.bugcode.cn/t/105350)
