### ISSUE TITLE
Plugin Options

### ISSUE THREAD

**Issue by Mr-Anonymous** [dmcBig/cordova-plugin-mediaPicker#5]
With the args, am I able to add other settings like: quality, encodingType, targetWidth, targetHeight, correctOrientation, etc? In the Image Picker plugin, I used to have the options like this:

```
var options = {
                    quality: 50,
                    destinationType: Camera.DestinationType.FILE_URI,
                    sourceType: srcType,
                    encodingType: Camera.EncodingType.JPEG,
                    mediaType: Camera.MediaType.PICTURE,
                    targetWidth: 1800,
                    targetHeight: 1200,
                    correctOrientation: true
              }
```

Out of the above, the main ones I want are the quality, targetWidth and encodingType (if possible). I found these reduce the uploading time by a lot since some high resolution full quality full size images can be very large. 

Is that possible with this plugin? What are the args settings available other than `selectMode`, `maxSelectCount` and `maxSelectSize`?

**Comment by Mr-Anonymous** [comment]
Sorry, 1 more question. Does this plugin need any additional settings for getting gallery access permission in the android and ios devices?

**Comment by dmcBig** [comment]
Q1：sorry not support quality and targetWidth ，Currently only these three parameters are supported。
Q2：No need to set extra

**Comment by Mr-Anonymous** [comment]
Thank you so much for your suggestion @dmcBig 

I will give giantss plugin a try as well.

**Comment by Mr-Anonymous** [comment]
I tried the giantss plugin and I feel your plugin probably still fits my needs. Would you consider added the quality and targetWidth parameters for image uploads? If its possible, do you know when you might be able to add it in? Thank you @dmcBig

**Comment by dmcBig** [comment]
I did not plan to join these parameters。

**Comment by Mr-Anonymous** [comment]
Fair enough. I will still watch your plugin incase you have plans in the future.

**Comment by dmcBig** [comment]
ok

**Comment by Mr-Anonymous** [comment]
After trailing and testing this plugin, I have added this to my production app since it perfectly fits my need. I love the Media picker and its really awesome especially in Android. However, I really wish you would reconsider adding the `quality` option to this plugin. That is 1 feature I really miss. Most phones now-a-days have really good cameras that takes high resolution pictures. Uploading these photos in full quality takes too much time since they are huge file size. Most of the time, such high quality will not be needed in applications. For instance, I tried uploading 30 photos taken from my camera and the upload took more than 5 mins to complete. If the quality of the image could have been reduced to 50%, then the upload would have completed considerably faster, as less as just 2 mins. Can you consider adding the quality options, atleast for the image uploads, please?
