### ISSUE TITLE
Please add iOS support for preview imgage

### ISSUE THREAD

**Issue by jiwufeiyang** [dmcBig/cordova-plugin-mediaPicker#7]
Hi,
Your plugin is very good. Can you add the function of previewing pictures in IOS like Android?

**Comment by jiwufeiyang** [comment]
大神你好，这个仿微信视频图片选择器做得很好，我的需求是多图预览取图，我在安卓上运行很成功，但是在苹果上安装这个插件时运行的效果只能取多张图片没有预览的功能，可以有空的时候加上这个功能吗？谢谢！

**Comment by dmcBig** [comment]
ok

**Comment by Mr-Anonymous** [comment]
That is fantastic. I love the way the plugin looks in Android. It be awesome if you can create similar looking layout for iOS as well. Also in iOS, it shows `all` at the top which doesn't look professional and will be good if you can improve this plugin theme in iOS. Awesome job so far.

**Comment by Mr-Anonymous** [comment]
Hi @dmcBig May I ask, would you be updating the plugin's iOS theme / layout? Is it possible to make it look similar to the way it looks in Android? as in black layout, with previews, etc. Any ETA on this so I can plan accordingly? Thanks.

**Comment by dmcBig** [comment]
@Mr-Anonymous  This black layout demand will be placed behind the drop-down selection album
