### ISSUE TITLE
Quality Option for Image Uploads

### ISSUE THREAD

**Issue by Mr-Anonymous** [dmcBig/cordova-plugin-mediaPicker#8]
This is in continuation to my previous request that was closed: https://github.com/dmcBig/cordova-plugin-mediaPicker/issues/5

I am creating this since my specific request is only for the `quality` option in plugin. Since the other issue was closed, here is my request information:

After trailing and testing this plugin, I have added this Media Picker plugin to my production app since it perfectly fits my need. I love the Media picker and its really awesome especially in Android. However, I really wish you would reconsider adding the `quality` option to this plugin. That is 1 feature I really miss. 

Most phones now-a-days have really good cameras that takes high resolution pictures. Uploading these photos in full quality takes too much time since they are huge file size. Most of the time, such high quality will not be needed in applications. For instance, I tried uploading 30 photos taken from my camera and the upload took more than 5-10 mins to complete. If the quality of the image could have been reduced to 50%, then the upload would have completed considerably faster, as less as just 2-3 mins. Can you consider adding the quality options for the image uploads, please? Or perhaps set the default quality at 50%?

**Comment by dmcBig** [comment]
I thought about your proposal carefully and I will add this feature
