### ISSUE TITLE
App Crashes in Android when opening Photo Library

### ISSUE THREAD

**Issue by Mr-Anonymous** [dmcBig/cordova-plugin-mediaPicker#9]
A user using this plugin in Android had reported that the App crashes everytime she tries to access the Photo Library. I asked the user to uninstall and reinstall the App again and she said the first time she opens the Media Picker, it asks for permission. After the permission is granted and she tries to open it, the App crashes and close down the App. She has been unable to get to the Library using the Media Picker plugin.

I am unable to reproduce the same in my phone since the plugin seems to work in the Android devices we have tested. However, this user is unable to use this plugin for her Android and it crashes. This issue is from my production app currently listed in Play store. Can you assist me please.

User's Android Set-up:

```
OS: android 6.0.1 
Browser: chrome 66.0.3359.158 
Device: android 
```

Here is the list of all other plugins I use:

```
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

Here is the ionic info of my app:
```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.4
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v9.3.0
    npm        : 5.7.1 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

Could the problem be because I have used Android 7 when I built the platform but this user seems to be using Android 6.0.1? Or is the problem related to something else?

**Comment by Mr-Anonymous** [comment]
Hi @dmcBig 

Thank you for getting back to me.

Another 2 users reported now with the same issue that the App crashes as soon as they click the button to add photos from their photo library. One of them has this configuration:

```
OS: android 8.0.0 
Browser: chrome 66.0.3359.158 
Device: android 
```

So it appears a few android devices so far are having this issue. I have asked them for the model and storage details of their device and will let you know when they get back to me on those.

**Comment by Mr-Anonymous** [comment]
No not yet. It was the version before that update. I last updated this plugin on May 12, I think the last commit at that time was the `ios gif icon` commit: https://github.com/dmcBig/cordova-plugin-mediaPicker/commit/1991181396f732ba16c5a4ed100792dcda539c6b

**Comment by dmcBig** [comment]
I tested several phones that passed the test. The test system had 8.0  7.0  6.0 5.0, but I tested it with the latest version. 

Tell me about your configuration : <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="25" /> in AndroidManifest.xml

**Comment by dmcBig** [comment]
I tested several phones that passed the test. The test system had 8.0 7.0 6.0 5.0, but I tested it with the latest version.

Tell me about your configuration : “\<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="21" /\>”  in AndroidManifest.xml

**Comment by Mr-Anonymous** [comment]
Sorry my bad. Pasted the wrong Manifest file. Here is my AndroidManifest.xml

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="20000201" android:versionName="2.0.2" package="com.example.examplemobile" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@mipmap/icon" android:label="@string/app_name" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTask" android:name="MainActivity" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="example" />
            </intent-filter>
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:host="www.example.com" android:pathPrefix="/app" android:scheme="https" />
                <data android:host=" " android:pathPrefix="/" android:scheme=" " />
                <data android:host=" " android:pathPrefix="/" android:scheme=" " />
                <data android:host=" " android:pathPrefix="/" android:scheme=" " />
                <data android:host=" " android:pathPrefix="/" android:scheme=" " />
            </intent-filter>
        </activity>
        <provider android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true" android:name="org.apache.cordova.camera.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/camera_provider_paths" />
        </provider>
        <provider android:authorities="${applicationId}.opener.provider" android:exported="false" android:grantUriPermissions="true" android:name="io.github.pwlin.cordova.plugins.fileopener2.FileProvider">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/opener_paths" />
        </provider>
    </application>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="26" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

```

**Comment by dmcBig** [comment]
sir user this get crash detail 
https://azure.microsoft.com/en-us/services/hockeyapp/
Get crash details I can help you find the reason

**Comment by Mr-Anonymous** [comment]
Hi @dmcBig

Its difficult for me to ask my users to install hockeyapp, send the crash data, etc. My users are usually older and have just enough knowledge to use iPads and phone apps. So asking them for crash reports will not be possible since its beyond their scope nor will they take the time to do that. 

But I have gathered as much information I can possible can from them. 2 users have told me the configurations and these are what I know:

User 1 uses:
```
Phone is: Oppo
Storage: Photos saved in Phone
OS: android 6.0.1 
Browser: chrome 66.0.3359.158 
```
User 2 uses:
```
Phone: HTC 10
Storage: (suspecting its from phone since user did not answer that question)
OS: android 8.0.0 
Browser: chrome 66.0.3359.158 
```
Hope the above helps out in some ways. Let me know if you find anything. Thank you for your support.

Thanks,
Neel.

**Comment by dmcBig** [comment]
hockeyapp is a cordova plugin 。when your app crash this plugin auto upload crash log。

**Comment by dmcBig** [comment]
hi sir where are you from

**Comment by Mr-Anonymous** [comment]
hmm. ok. When I read it thought it was an App user needs to install in the device to send crash report. I will review it if its a cordova plugin and will release an update with it then. Thank you for pointing it out.

And, my users and I are from Australia, although I am in India now for vacation.

**Comment by dmcBig** [comment]
It's embarrassing that the exception of the plug-in disturbs your holiday, and I'll try to find the problem.

But the necessary conditions to be solved
1. I can find a phone to reproduce
2. Crash log

**Comment by Mr-Anonymous** [comment]
Its no problem at all. I am always working. I am grateful for your support since other plugins I used before this (telerik and wymsee) has zero support and they had other problems too. So, all good. Infact couple of users had even said that this new Android plugin (yours) we have in our app is so much better than before. So thats positive. It appears some can use it and they love it while its only some having crash issues when opening the library.

I am currently looking into the cordova plugin for crash report. But it could be a long process since I need to update the app, ask the user to install it, its weekend soon and not sure if the users will do it straight away and then wait. Fingers crossed. Will let you know if I get any more info.

**Comment by dmcBig** [comment]
http://utest.21kunpeng.com/
i test  oppo and htc 10 not reproduce crash

**Comment by Mr-Anonymous** [comment]
hmm.. thats good to know. then i guess the crash report is what I need to get hold of to know exactly whats happening in that device.

**Comment by Mr-Anonymous** [comment]
Hi @dmcBig 

I have gathered the crash report from Google Play console. I am attaching the screenshots. Does this give you the info that you needed?

<img width="1001" alt="crashes" src="https://user-images.githubusercontent.com/8770270/40168298-c8810532-59e0-11e8-8e89-28a473218e66.png">
Oppo Crash Report:
<img width="976" alt="oppo-crash-report" src="https://user-images.githubusercontent.com/8770270/40168319-d1aeccfc-59e0-11e8-8067-34822d29fc30.png">
HTC Crash Report:
<img width="975" alt="htc-crash-report" src="https://user-images.githubusercontent.com/8770270/40168363-eb5909f6-59e0-11e8-8f4d-2709597d7933.png">

If the above is sufficient, then I might not look into installing the Crashlytics plugin.

Thanks,
Neel.

**Comment by dmcBig** [comment]
good ,The reason for the problem is simple because the picture does not have a suffix name or extension. I immediately fix it

**Comment by Mr-Anonymous** [comment]
Awesome. Thank you so much for that. The crashes apparently happened even before selecting the picture, as in, when its supposed to open the library with the listings and not after selecting the pictures. So did the picture suffix cause this behaviour in phone?

**Comment by Mr-Anonymous** [comment]
One more thing, I use plugman to install or update the plugin. To update the plugin I just remove and add the platforms to make sure and do this:
```
plugman install --platform android --project platforms/android --plugin cordova-plugin-mediapicker-dmcbig
```
Is it fine to update to the latest version of this plugin using `cordova-plugin-mediapicker-dmcbig` or should I use a direct url to git?

**Comment by dmcBig** [comment]
delete plugin ,add plugin .  

Because I want to display the GIF icon in my selection interface, and how to know if a picture is a GIF, I use the extension. This method is not very beautiful, but Android seems to be the simplest way.

**Comment by Mr-Anonymous** [comment]
perfect. I will update my plugin once you push through the update. Thank you. You have been very helpful indeed.

**Comment by dmcBig** [comment]
The core package of the Android plugin has been updated, the core package is in Jcenter/Bintray, so you can remove the plugin and add it again and get the new version.

This can reproduce the bug, remove the picture extension suffix name

**Comment by Mr-Anonymous** [comment]
Brilliant. Thank you @dmcBig

**Comment by Mr-Anonymous** [comment]
Hi @dmcBig 

I removed my old mediapicker plugin and reinstalled the new one. But everytime I reinstall this plugin and run the build, I kept bumping into this exception while executing the task `:app:processDebugManifest` during build time at the end:
```
:app:processDebugManifest
/example/platforms/android/app/src/main/AndroidManifest.xml:39:5-108 Error:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:39:5-108 duplicated with element declared at AndroidManifest.xml:36:5-81
/example/platforms/android/app/src/main/AndroidManifest.xml Error:
	Validation failed, exiting
```
The AndroidManifest.xml line 36-39 is:

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:maxSdkVersion="18" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
So the second declaration for `WRITE_EXTERNAL_STORAGE` had to be removed: 
```
File: platforms/android/app/src/main/AndroidManifest.xml 

<uses-permission android:maxSdkVersion="18" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
But everytime I build it, the second `WRITE_EXTERNAL_STORAGE` permission keeps getting added giving with the same error.
    
Am I making a mistake somewehere? I dont know if its related to a conflict with 2 plugins. Here is my plugins list apart from your one:

```
cordova-android-support-gradle-release 1.4.2 "cordova-android-support-gradle-release"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-ignore-lint-translation 0.0.1 "cordova-plugin-ignore-lint-translation"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-ios-camera-permissions 1.2.0 "iOS Permissions"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

Any suggestions please?

**Comment by dmcBig** [comment]
plugin conflict

**Comment by Mr-Anonymous** [comment]
Thanks. I am now able to build android after updating the plugin.
